package fields

const (
	APIToken    = "api_token"
	APIVersion  = "api_version"
	Environment = "catchpoint_environment"
	LogJSON     = "log_json"
)

const (
	DivisionID  = "division_id"
	FolderName  = "folder_name"
	ID          = "id"
	Name        = "name"
	ParentID    = "parent_id"
	ProductName = "product_name"
	String      = "string"
	Value       = "value"
	Values      = "values"
	Key         = "key"
	Email       = "email"
)

const (
	CertificateName              = "certificate_name"
	AdvancedSettings             = "advanced_settings"
	AlertsPaused                 = "alerts_paused"
	CertificateThumbprintValue   = "certificate_thumbprint_value"
	ChangeDate                   = "change_date"
	EnableTestDataWebhook        = "enable_test_data_webhook"
	EndTime                      = "end_time"
	EnforceCertificateKeyPinning = "enforce_certificate_key_pinning"
	EnforceCertificatePinning    = "enforce_certificate_pinning"
	FileData                     = "file_data"
	FolderID                     = "folder_id"
	GatewayAddressOrHost         = "gateway_address_or_host"
	Insights                     = "insights"
	Label                        = "label"
	Monitor                      = "monitor"
	PassPhrase                   = "passphrase"
	Prefix                       = "prefix"
	ProductID                    = "product_id"
	PublicKeyThumbprintValue     = "public_key_thumbprint_value"
	RequestSettings              = "request_settings"
	ScheduleSettings             = "schedule_settings"
	StartTime                    = "start_time"
	Status                       = "status"
	TestDescription              = "test_description"
	TestLocation                 = "test_location"
	TestName                     = "test_name"
	TestURL                      = "test_url"
	URL                          = "url"
)

const (
	AdvancedSettingType   = "advanced_setting_type"
	AppliedTestFlags      = "applied_test_flags"
	Authentication        = "authentication"
	ChildHostPattern      = "child_host_pattern"
	Frequency             = "frequency"
	HeaderName            = "header_name"
	HTTPRequestHeaders    = "http_request_headers"
	InsightSettingType    = "insight_setting_type"
	IndicatorIDs          = "indicator_ids"
	LibraryCertificateIDs = "library_certificate_ids"
	MaintenanceScheduleID = "maintenance_schedule_id"
	NetworkType           = "network_type"
	NodeDistribution      = "node_distribution"
	NodeGroupIDs          = "node_group_ids"
	NodeGroups            = "node_groups"
	NodeIDs               = "node_ids"
	Nodes                 = "nodes"
	NoOfSubsetNodes       = "no_of_subset_nodes"
	RequestHeaderType     = "request_header_type"
	RequestSettingType    = "request_setting_type"
	RequestValue          = "request_value"
	RunScheduleID         = "run_schedule_id"
	ScheduleSettingType   = "schedule_setting_type"
	TokenIDs              = "token_ids"
	TracepointIDs         = "tracepoint_ids"
)

const (
	ChromeVersion  = "chrome_version"
	TestScript     = "test_script"
	TestScriptType = "test_script_type"
	UserAgentType  = "user_agent_type"
	Simulate       = "simulate"
)

const (
	AlertGroupID              = "alert_group_id"
	AlertRule                 = "alert_rule"
	AlertSettings             = "alert_settings"
	AlertSettingType          = "alert_setting_type"
	AlertSubType              = "alert_sub_type"
	AlertType                 = "alert_type"
	AlertWebhookIDs           = "alert_webhook_ids"
	AvailabilityCritical      = "availability_critical"
	AvailabilityWarning       = "availability_warning"
	ConsecutiveNumberOfRuns   = "consecutive_number_of_runs"
	ContactGroupIDs           = "contact_group_ids"
	CriticalReminder          = "critical_reminder"
	CriticalTrigger           = "critical_trigger"
	EnableConsecutive         = "enable_consecutive"
	EnforceTestFailure        = "enforce_test_failure"
	Expression                = "expression"
	HistoricalInterval        = "historical_interval"
	NodeThresholdType         = "node_threshold_type"
	NotificationGroup         = "notification_group"
	NotificationType          = "notification_type"
	NotifyOnCritical          = "notify_on_critical"
	NotifyOnImproved          = "notify_on_improved"
	NotifyOnWarning           = "notify_on_warning"
	NumberOfFailingNodes      = "number_of_failing_nodes"
	OmitScatterplot           = "omit_scatterplot"
	OperationType             = "operation_type"
	RecipientEmails           = "recipient_emails"
	StatisticalType           = "statistical_type"
	Subject                   = "subject"
	TestDataWebhookID         = "test_data_webhook_id"
	TestTimeCritical          = "test_time_critical"
	TestTimeWarning           = "test_time_warning"
	ThresholdInterval         = "threshold_interval"
	ThresholdNumberOfRuns     = "threshold_number_of_runs"
	ThresholdPercentageOfRuns = "threshold_percentage_of_runs"
	Thresholds                = "thresholds"
	TriggerType               = "trigger_type"
	UseRollingWindow          = "use_rolling_window"
	WarningReminder           = "warning_reminder"
	WarningTrigger            = "warning_trigger"
	RecipientType             = "recipient_type"
	FilterType                = "filter_type"
	FilterValue               = "filter_value"
	Level                     = "level"
	AllMatchRecords           = "all_match_records"
)

const (
	DNSServer       = "dns_server"
	QueryType       = "query_type"
	TestDomain      = "test_domain"
	DNSRecordType   = "dns_record_type"
	DNSttl          = "dns_ttl"
	DNSResolvedName = "dns_resolved_name"
)

// Paths for the patch docs.
const (
	AdvancedSettingsModelSection = "/advancedSettingsModel" ///< advancedSettingsModel is for Product
	AdvancedSettingsSection      = "/advancedSettings"      ///< advancedSettings is for Folder and Test
	AlertGroupSection            = "/alertGroup"
	AlertsPausedSection          = "/alertsPaused"
	// ApplicationVersionIDSection         = "/applicationVersionId"
	// ApplicationVersionTypeSection       = "/applicationVersionType"
	ChromeMonitorVersionSection         = "/chromeMonitorVersion"
	DescriptionSection                  = "/description"
	DNSQueryTypeSection                 = "/dnsQueryType"
	DNSServerSection                    = "/dnsServer"
	EnableTestDataWebhookSection        = "/enableTestDataWebhook"
	EndTimeSection                      = "/endTime"
	EnforceCertificateKeyPinningSection = "/enforceCertificateKeyPinning"
	EnforceCertificatePinningSection    = "/enforceCertificatePinning"
	FrequencySection                    = "/frequency"
	GatewayAddressOrHostSection         = "/gatewayAddressOrHost"
	IndicatorsSection                   = "/indicators"
	InsightsSection                     = "/insights"
	InsightDataSection                  = "/insightData"
	InsightsDataSection                 = "/insightsData"
	InsightSettingTypeSection           = "/insightSettingType"
	TracepointsSection                  = "/tracepoints"
	LabelsSection                       = "/labels"
	MaintenanceScheduleIDSection        = "/maintenanceScheduleId"
	MonitorSection                      = "/monitor"
	NameSection                         = "/name"
	NodeDistributionSection             = "/testNodeDistribution"
	NodeGroupsSection                   = "/nodeGroups"
	NodesSection                        = "/nodes"
	RequestSettingSection               = "/requestSetting"
	RequestSettingsSection              = "/requestSettings"
	RoundRobinAmountSection             = "/roundRobinAmount"
	RunScheduleIDSection                = "/runScheduleId"
	ScheduleSettingSection              = "/scheduleSetting"  ///< Folders
	ScheduleSettingsSection             = "/scheduleSettings" ///< Tests and Products
	ScheduleSettingTypeSection          = "/scheduleSettingType"
	SimulateSection                     = "/userAgentTypeId"
	StartTimeSection                    = "/startTime"
	StatusSection                       = "/status"
	TestDataWebhookIDSection            = "/testDataWebhookId"
	TestRequestDataSection              = "/testRequestData"
	ThresholdRestModelSection           = "/thresholdRestModel"
	TransactionScriptTypeSection        = "/transactionScriptType"
	URLSection                          = "/url"
	ParentIDSection                     = "/parentId"
	ProductIDSection                    = "/productId"
	FolderIDSection                     = "/folderId"
)

const (
	AuthenticationType = "authentication_type"
	PasswordIDs        = "password_ids"
)

// AdvancedSettings
const (
	EDNSSubnet                         = "edns_subnet"
	PingCount                          = "ping_count"
	FailureHopCount                    = "failure_hop_count"
	ViewportWidth                      = "viewport_width"
	ViewportHeight                     = "viewport_height"
	WaitForNoActivity                  = "wait_for_no_activity"
	EnforceTestFailureIfRunsLongerThan = "enforce_test_failure_if_runs_longer_than"
	StopTestOnDocumentComplete         = "stop_test_on_document_complete"
	AdditionalMonitor                  = "additional_monitor"
	BandwidthThrottling                = "bandwidth_throttling"
)
